* Experiment
** Phase 1
[[https://drive.google.com/drive/folders/1hVNusbqG1V_bV46qzrIVKRSIUHX2HnVA?usp=drive_link][This our curated dataset]] of ethnic word-contained articles from [[https://www.kaggle.com/datasets/ebiswas/bangla-largest-newspaper-dataset][ebD- Bangla newspaper dataset.]] We have curated ethnic people related dataset using simply keyword based extraction. We considered the following keywords to filter out the articles.
#+begin_src python
  ethnic_tribe_names = [
    "চাকমা", "মারমা", "সাঁওতাল", "ত্রিপুরা", "গারো", "ওঁরাও", "তঞ্চ্যঙ্গা", "ম্রো", 
    "পাংখো", "চাক", "খেয়াং", "খুমি", "লুসাই","কুকি", "রাখাইন", "মণিপুরী",
    "হাজং", "খাসিয়া", "মং", "বর্মন", "পাহাড়ি", "মালপাহাড়ি", "মুন্ডা", "ভূমিজ",
    "কন্দ", "পাঙন", "লাওরা", "মুরং", "বাগদী"
] #"বম","কোচ","ডালু","কোল", "রাজবংশী", "পাত্র", "ভিল", "গণ্ড", "খাসি"

ethnicity_directed_words = [
    "আদিবাসী" , "আদিবাসি" , "উপজাতি", "নৃগোষ্ঠী"
]
#+end_src

Following are the dimensions of resulting datasets.
| Dataset                     |             Size | Approach           | Comment                                                                |
| [[https://www.kaggle.com/datasets/ebiswas/bangla-largest-newspaper-dataset][eBD Bangla news]]             | 2294710 articles | -                  | -                                                                      |
| Curated Ethnic Word Dataset |  337793 articles | Keyword Extraction | Buggy, For list of articles, same list is added continuously.          |
| Target Ethnic Articles      |            14000 | 5 Keyword          | Topic modeling result came out bad due to repetition.                  |
| Curated Ethnic Word Dataset |            [[https://drive.google.com/file/d/1xiJXor4yKYnEyNPEdFhAQfOkl8tf4Gsz/view?usp=drive_link][10187]] | Keyword Extraction | Fixed the bug where same article was being added for each of its words |
| Most Relevant Articles      |              221 | 5 Keywords         |                                                                        |

The only preprocessing we did was this -> ~to_remove = ['email\xa0protected', '\n\n\n\xa0\n\n\n\n\n', '\u200c্', '\n\n', '\xa0', '\n']~. These are the top 10 topics we found in the articles.
#+begin_src text
Topic 0: "পার্বত্য" "চট্টগ্রাম" "উপজেলার" "ত্রিপুরা" "প্রাথমিক" "শিশুদের" "বিভিন্ন" "উন্নয়ন" "পাঠ্যপুস্তক" "চেয়ারম্যান"
Topic 1: "তঞ্চঙ্গ্যা" "সম্প্রদায়" "উৎসবকে" "তরুণীরা" "পাহাড়ের" "পুরাতন" "নেওয়ার" "লকডাউন" "বান্দরবানে" "সাঙ্গু"
Topic 2: "আদিবাসী" "পরিষদের" "আওয়ামী" "সভাপতি" "সম্পাদক" "বক্তব্য" "পার্বত্য" "আদিবাসীদের" "সাধারণ" "চেয়ারম্যান"
Topic 3: "বৈসাবি" "সাংগ্রাই" "সম্প্রদায়ের" "পাহাড়ি" "ঐতিহ্যবাহী" "এপ্রিল" "অনুষ্ঠান" "উৎসবের" "অনুষ্ঠিত" "প্রধান"
Topic 4: "জন্মদিনকে" "ছোটাছুটি" "নালন্দার" "দলবদ্ধ" "দলগতভাবে" "নৃত্যকলা" "জন্মদিন" "গ্যালারির" "চতুর্থতলায়" "নৃত্যসহ"
Topic 5: "বাংলাদেশে" "হিন্দু" "সাম্প্রদায়িক" "আক্রমণ" "সাম্প্রদায়িকতা" "ধর্মীয়" "কিন্তু" "লোকদের" "মুসলমান" "সাম্প্রদায়িকতার"
Topic 6: "গ্রামের" "উপজেলার" "মেহেরপুর" "জয়পুরহাট" "উদ্দিনের" "বেনাপোল" "পাঁচবিবি" "সাতক্ষীরা" "চুয়াডাঙ্গা" "নববর্ষ"
Topic 7: "পার্বত্য" "বিরুদ্ধে" "ভারতের" "বাহিনীর" "হিসেবে" "বাংলাদেশ" "উপজাতি" "সরকারের" "প্রবেশ" "নির্বাচিত"
Topic 8: "ক্ষুদ্র" "গোষ্ঠীর" "বাঙালি" "সংস্কৃতি" "বিভিন্ন" "ত্রিপুরা" "নিজস্ব" "বাংলাদেশ" "কিন্তু" "বাংলাদেশের"
Topic 9: "বাংলাদেশের" "আমাদের" "বাঙালি" "বাংলাদেশে" "বিভিন্ন" "বাংলাদেশ" "ধর্মের" "মানুষের" "ত্রিপুরা" "প্রশ্ন"
#+end_src

Clearly, stemming is needed here. We used [[https://github.com/Foysal87/sbnltk/blob/main/docs/Stemmer.md][SBNLTK]] Stemmer here because this project is the largest BNLP library and the developer seems pretty active. After stemming, we got the following topics.
#+begin_src text
Topic 0: "গোষ্ঠী" "আমা" "ক্ষুদ্" "পৃথিবী" "মেয়ে" "অধিকাংশ" "গুরুত্ব" "মানুষ" "অধিবাসী" "ত্রিপুরা"
Topic 1: "পার্বত্য" "চট্টগ্রাম" "আদিবাসী" "শিক্ষার্থী" "পরিষদ" "চেয়ারম্যান" "প্রাথমিক" "ক্ষুদ্" "সভাপতি" "শিশু"
Topic 2: "বাংলাদেশ" "হিন্দু" "ভারত" "বিরুদ্ধ" "সংখ্যালঘু" "নির্যাতন" "প্রশ্ন" "আক্রমণ" "কিন্তু" "সাম্প্রদায়িক"
Topic 3: "মুক্তিযোদ্ধা" "স্বাধীনতাযুদ্ধে" "জামুকা" "পদ্ধতিগত" "শিববাড়ি" "লক্ষ্যবস্তু" "কাক্সিক্ষত" "ইদ্রিস" "অ্যাম্বুশ" "করোইয়ে"
Topic 4: "উপজেল" "আওয়ামী" "ইউনিয়ন" "পরিবার" "উদ্দিন" "এলাকা" "সাম্প্রদায়িকতা" "স্থানীয়" "উপজেলা" "বিএনপি"
Topic 5: "সম্প্রদায়" "পাহাড়" "ত্রিপুরা" "অনুষ্ঠান" "শ্রেণি" "উৎসব" "সাংস্কৃতিক" "প্রধান" "তঞ্চঙ্গ্যা" "বাস্তবায়ন"
Topic 6: "পাহাড়" "আশ্রম" "বান্দরবান" "পরিবহন" "ব্যাখ্যা" "সাঙ্গু" "প্রকৃতি" "যাত্" "দূরত্ব" "ধর্মমত"
Topic 7: "অনেকদিন" "অভিনয়ের" "রফিকুন" "সনদপত্র" "সাইফু" "স্মৃতিকাতর" "স্লাইড" "হুটোপুটি" "অধ্যবসায়ী" "অনেককিছু"
Topic 8: "বাংলাদেশ" "বাঙা" "আমা" "বিভিন্ন" "মানুষ" "আদিবাসী" "ক্ষুদ্" "সাঁওতাল" "নিজস্ব" "জনগোষ্ঠী"
Topic 9: "গ্রাম" "সীমান্ত" "বিহার" "বর্ণমালা" "পদ্ধতি" "প্রাচীন" "দক্ষিণ" "মেহেরপুর" "ব্যবহার" "জয়পুরহাট"
DataFrame shape(10, 2)
#+end_src

This time, we did LDA on the eniter [[https://drive.google.com/file/d/1xiJXor4yKYnEyNPEdFhAQfOkl8tf4Gsz/view?usp=drive_link][10187]] articles containing ethnic words. We ended up with the following topics.
#+begin_src text
Topic 0:"পার্বত্য" "প্রধানমন্ত্রী" "বাংলাদেশ" "চট্টগ্রাম" "চাকমা" "ত্রিপুরা" "খাগড়াছড়ি" "ইউপিডিএফ" "বিএনপি" "রাঙ্গামাট"
Topic 1:"শিক্ষা" "শিক্ষক" "সরকারি" "প্রাথমিক" "চাকরিতে" "সন্তান" "প্রশিক্ষণ" "বিদ্যাল" "শিশু" "সংস্ক"
Topic 2:"নির্বাচন" "প্রার্থী" "স্বাস্থ্য" "মুক্তিযোদ্ধা" "মোহাম্মদ" "পরিকল্পনা" "নির্বাচিত" "জানা" "পেয়" "শক্তিমান"
Topic 3:"উপজেলা" "সম্পাদক" "উপজেল" "চেয়ারম্যান" "আওয়ামী" "সভাপতি" "ইউনিয়ন" "সাধারণ" "শিক্ষার্থী" "চৌধুরী"
Topic 4:"আক্তার" "বৃহস্পতিব" "চন্দ্" "হাইকোর্ট" "ওবায়দুল" "মিয়ানমারে" "মোবাইল" "উদ্দিন" "মোটরসাইকেল" "দুর্ঘটনা"
Topic 5:"এলাকা" "গ্রাম" "হাসপাতাল" "স্থানীয়" "পরিবার" "অভিযান" "সন্ত্রাসী" "নিশ্চিত" "গ্রেফতার" "নির্মাণ"
Topic 6:"বাংলাদেশ" "আমা" "কিন্তু" "মানুষ" "হিস" "কর" "অধিক" "ক্ষেত্র" "আন্দোলন" "মাধ্যম"
Topic 7:"অভিযোগ" "পুলিশ" "উদ্ধ" "কর্মকর্তা" "বিরুদ্ধ" "ঘটনাস্থল" "এলাক" "বিষয়টি" "চট্টগ্রাম" "মামল"
Topic 8:"রোহিঙ্গা" "বাংলাদেশ" "সরকার" "রাখাইন" "মিয়ানমারের" "কক্সবাজার" "ক্যাম্প" "মিয়ানমার" "সেনাবাহিনী" "রাজ্য"
Topic 9:"উন্নয়ন" "পাহাড়" "ক্ষুদ্" "বিভিন্ন" "গোষ্ঠী" "উৎসব" "পাহাড়" "উদ্যোগ" "পরিচিত" "সামাজিক"
#+end_src

The topics are interesting. We feel like the quality of our articles are not very good. We will verify this claim by considering coherence score. If coherence score is good and we still get such terrible topics, then most of articles just happen to contain ethnic people's names and they are not ethnic people related. In that case,

- [ ] Use semi-supervised seeded LDA
- [ ] Get word cloud for ethnic articles
- [ ] Use doc2vec to convert articles to vectors and then use consine_similarity(doc2vec, ethnic_vector) to filter out articles that are actually ethnic people related.
** Phase 2
*** Perform Word Embedding to pick relevant words
The dataset is large. So we will do the following.
- [ ] In one colab, we will first conver the dataset into the bow form that the model needs. We will then save it.
- [ ] Send batch by batch and use checkpointing. After training for 5min, stop training. See the status of the checkpoint.
- [ ] Schedule and plan checkpoint based word embedding training.
*** Estimate word frequency
*** Survey
* Resources
[[https://drive.google.com/drive/folders/1hVNusbqG1V_bV46qzrIVKRSIUHX2HnVA?usp=drive_link][This is the shared drive]] with literature review and motivation behind the task.

We have also found some notebooks on bangla topic modeling.

| Noteook                                               | Year | Approach      |
| [[https://github.com/aljubaer/Topic-Modeling-in-Bengali]] | 2019 | Gensim TF-IDF |
|                                                       |      |               |
